# FVA from a reference solution

Here we use a different strategy where we use the previous uptake fluxes from a MICOM result and run an FVA on the exchanges. 

This will impose an upper bound equal to the import from the reference solution, but can tell you if there is flexibility in this uptake.

In [1]:
from micom.workflows import load_results

res = load_results("results.zip")

We will now use the results a basis for running FVA with the fixed uptakes from the solution.

In [2]:
from fva import eFVA

results = eFVA(
    results=res,
    model_db="agora103_refseq216_genus_1.qza",
    taxa=["Anaerostipes"],
    fva_threshold=0.99,
    threads=4
)

In [3]:
results

,minimum,maximum,reaction,sample_id,metabolite,name,molecular_weight,C_number,N_number,hmdb,inchi,kegg.compound,pubchem.compound,chebi
0,0.000000,0.000000,EX_4abut(e),ERR1883212,4abut[e],4-Aminobutanoate,103.11976,4,1,HMDB00112,"InChI=1S/C4H9NO2/c5-3-1-2-4(6)7/h1-3,5H2,(H,6,7)",C00334,119.0,NaN
1,0.000000,0.000000,EX_MGlcn10(e),ERR1883212,MGlcn10[e],mucin-type O-glycan No 10,NaN,44,4,NaN,NaN,NaN,NaN,NaN
2,0.000000,0.000000,EX_MGlcn104(e),ERR1883212,MGlcn104[e],mucin-type O-glycan No 104,NaN,46,2,NaN,NaN,NaN,NaN,NaN
3,0.000000,0.000000,EX_MGlcn104_rl(e),ERR1883212,MGlcn104_rl[e],released mucin-type O-glycan No 104,1219.10392,46,2,NaN,NaN,NaN,NaN,NaN
4,0.000000,0.000000,EX_MGlcn105(e),ERR1883212,MGlcn105[e],mucin-type O-glycan No 105,NaN,46,2,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2899,0.000000,0.000000,EX_tsul(e),ERR1883250,tsul[e],thiosulfate(2-),112.12820,0,0,HMDB00257,"InChI=1S/H2O3S2/c1-5(2,3)4/h(H2,1,2,3,4)/p-2",C05529,1084.0,NaN
2900,0.000000,0.000000,EX_ttdca(e),ERR1883250,ttdca[e],tetradecanoate (n-C14:0),227.36298,14,0,HMDB00806,InChI=1S/C14H28O2/c1-2-3-4-5-6-7-8-9-10-11-12-...,C06424,11005.0,NaN
2901,-18.751156,760.986269,EX_val_L(e),ERR1883250,val_L[e],L-valine,117.14634,5,1,HMDB00883,"InChI=1S/C5H11NO2/c1-3(2)4(6)5(7)8/h3-4H,6H2,1...",C00183,6287.0,NaN
2902,-100.000000,703.856930,EX_fum(e),ERR1883250,fum[e],Fumarate,114.05628,4,0,HMDB00134,"InChI=1S/C4H4O4/c5-3(6)1-2-4(7)8/h1-2H,(H,5,6)...",C00122,444972.0,NaN
2903,0.000000,0.000000,EX_hom_L(e),ERR1883250,hom_L[e],L-homoserine,119.11916,4,1,HMDB00719,"InChI=1S/C4H9NO3/c5-3(1-2-6)4(7)8/h3,6H,1-2,5H...",C00263,12647.0,NaN